package com.demo.common.model;

import com.demo.common.model.base.BaseTbUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbUser extends BaseTbUser<TbUser> {
	public static final TbUser dao = new TbUser().dao();

	public void save2(){
		dao.save();
	}
}
